name: homepage deploy pipline

on:
  push:
    tags:
      - '*'
    branches: [ main ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{github.repository}}

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency:
      group: ${{github.workflow}} - ${{github.ref}}
    
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          submodules: true
          fetch-depth: 0
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22.0.0'
        
      - name: install
        run: npm install 

      - name: build
        run: npm run build 

      - name: deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{github.ref == 'refs/heads/main'}}
        with: 
          github_token: ${{secrets.TOKEN}}
          publish_dir: ./dist
